### PR TITLE
Implement an AssetsPtr template that allows building on 64-bit systems

### LINKED ISSUE #107: 64-bit builds of the firmware can not run
eez::gui::assets is a big structure created by Studio that contains pointers. These pointers are relative to the start of the structure, and rewritten when loaded by the firmware. Unfortunately this does not work on 64-bit systems (e.g. simulation build on modern processors), because pointer sizes differ:

image

The '8' that should be the real pointer is taken to be padding, and the '1' is used instead, as can be seen in the printout at the bottom.

Possible solutions include:
- When initializing on a 64-bit system, parse the whole structure and make a copy that has the correct sizes
- Change all raw pointer types `T*` to a new class (e.g. `AssetsPtr<T>`) that is a raw pointer on 32-bit hardware and taken as an offset to `MEMORY_BEGIN` on 64-bits. This seems more elegant and should require less special code for 64-bit systems, but of course needs several small changes to remove all raw pointers from the relevant structures.

### PR DESCRIPTION
**Pull request by Cat-Ion**
Fixes #107
Content warning: Templates

### CODE REVIEW

**Comment by Cat-Ion** [comment]
I can't build the actual firmware yet, so this has only been tested on a 64-bit Linux system so far.

**Comment by Cat-Ion** [comment]
Looks like there's still some issues with Values, presumably because of the same thing... are those also all allocated in the 8-64 MB region at MEMORY_BEGIN? :S

**Comment by mvladic** [comment]
There is an error when compiling using Visual Studio 2017:

```
2>assets.cpp(81): error C2440: '=': cannot convert from 'uint8_t *' to 'T *'
2>        with
2>        [
2>            T=const char *
2>        ]
2>assets.cpp(81): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
```

**Comment by mvladic** [comment]
Value has an union which can hold pointers. It is possible that one of these AssetsPtr's are stored in there.

**Comment by mvladic** [comment]
Same error when compiling using Atollic TrueStudio (armgcc):

```
..\..\..\eez\gui\assets.cpp: In function 'void eez::gui::NameList_fixPointers(eez::gui::NameList*)':
..\..\..\eez\gui\assets.cpp:81:77: error: cannot convert 'uint8_t* {aka unsigned char*}' to 'eez::gui::AssetsPtr<const char*> {aka const char**}' in assignment
         nameList->first = ((uint8_t *)&*nameList + (uint32_t)nameList->first);
```

**Comment by Cat-Ion** [comment]
@mvladic We still need to figure out the Value instances that are used in some widgets. Are all the pointers used there to other assets, or can they be to things not stored on the SDRAM?

**Comment by Cat-Ion** [comment]
Okay, there's definitely places where pointers outside of the SDRAM are stored in Values. The options that come to mind now are

- Add padding to the one widget that contains a value. This is a dirty hack and needs to be repeated for each widget that gets a Value in the future. Also need to adjust the assets, because they'll be incompatible with the new firmware.
- Make all Values 64-bits. Might bloat the memory by a bit, depending on how many are used in the firmware, but probably shouldn't be a *huge* issue. Also leads to incompatible assets.
- If we need to keep assets compatible, then we can introduce a new Value that can not contain pointers outside of the assets structure, and can stay 32-bit-sized. It would convert cleanly to the normal Value, and converting a Value containing an asset pointer to this one would work - but it will break for other pointers, and seems a bit more fiddly.

**Comment by mvladic** [comment]
> yeah, it'll crash when you... select yt-graph and start a channel, IIRC

I found the reason for this particular crash (and possibly some others in 64-bit build). This:

```
    Value() 
        : type_(VALUE_TYPE_NONE), options_(0), unit_(UNIT_UNKNOWN) 
    {
        uint32_ = 0;
    }
```

should be initialized as this:

```
    Value() 
        : type_(VALUE_TYPE_NONE), options_(0), unit_(UNIT_UNKNOWN) 
    {
        pVoid_ = 0;
    }
```

This fixed the bug. But, we should also make getOverlay more robust:

```
Overlay *getOverlay(const WidgetCursor &widgetCursor) {
    if (widgetCursor.widget->type != WIDGET_TYPE_CONTAINER) {
        return nullptr;
    }
    const ContainerWidget *containerWidget = GET_WIDGET_PROPERTY(widgetCursor.widget, specific, const ContainerWidget *);
    if (containerWidget->overlay == DATA_ID_NONE) {
        return nullptr;
    }
    Value overlayValue;
    DATA_OPERATION_FUNCTION(containerWidget->overlay, DATA_OPERATION_GET_OVERLAY_DATA, (Cursor )widgetCursor.cursor, overlayValue);
    if (overlayValue.getType() == VALUE_TYPE_POINTER) {
        return (Overlay *)overlayValue.getVoidPointer();
    }
    return nullptr;
}
```

**Comment by mvladic** [comment]
On STM32CubeIDE:

image

**Comment by mvladic** [comment]
Otherwise, I tested it on BB3 and it works!

**Comment by Cat-Ion** [comment]
Awesome! With the latest commit nothing should be able to complain anymore, either :)

**Pull request merged**
